### ISSUE TITLE
Override SyntaxHighlighter.defaults thanks to mediaWiki conf

### ISSUE THREAD

**Issue by M3lkior** [seongjaelee/SyntaxHighlighter#6]
Hi @seongjaelee ,

It is possible to override SyntaxHighlighter.defaults without overloading your php file ?
If not, can you plan this enhancement ?

Thanks.

**Comment by seongjaelee** [comment]
Hi, sorry for my late response. I need more context to understand this issue. Could you explain more? What do you mean by "thanks to mediaWiki conf"? What is SyntaxHighlighter.defaults?

**Comment by M3lkior** [comment]
Here is the SyntaxHighlighter defaults options  : http://alexgorbatchev.com/SyntaxHighlighter/manual/configuration/#syntaxhighlighterdefaults
I wish to set toolbar option to false by default in my wiki but to do this, i have to set toolbar = false programmatically in SyntaxHighlighter.php, 

My proposal : having plugin options, configurable on LocalSettings.php like this : 

require_once("$IP/extensions/SyntaxHighlighter/SyntaxHighlighter.php");
$wgSyntaxHighlighterOption['toolbar'] = false
